// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsoqjnhktrjfqrbbflry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpzb3FqbmhrdHJqZnFyYmJmbHJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDU0OTQsImV4cCI6MjA2NTIyMTQ5NH0.V4a-TXo3D_WiI9smK3dKAvDtyJ9xboVzlr0074uJzx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);